# Generated by Django 3.2.3 on 2021-06-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_tag_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ingredientitem",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"),
                name="unique_recipe_ingredient",
            ),
        ),
    ]
