# Generated by Django 3.2.3 on 2021-06-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210604_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.AddField(
            model_name='tag',
            name='display_color',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='display_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
