# Generated by Django 3.2.3 on 2021-06-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_remove_ingredientitem_unique_recipe_ingredient"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                fields=("title", "dimension"), name="unique_recipe_ingredient"
            ),
        ),
    ]
