# Generated by Django 3.2.3 on 2021-06-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210604_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='display_color',
            new_name='color',
        ),
    ]
