# Generated by Django 3.2.3 on 2021-06-27 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_ingredient_unique_recipe_ingredient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredientitem",
            options={"verbose_name": "Ингредиент итем"},
        ),
    ]
