# Generated by Django 3.2.3 on 2021-06-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_rename_display_color_tag_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='display_name',
        ),
        migrations.AddField(
            model_name='tag',
            name='value',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
