# Generated by Django 3.2.3 on 2021-06-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0006_alter_ingredientitem_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredientitem",
            options={
                "verbose_name": "Ингредиент итем",
                "verbose_name_plural": "Ингредиент итемы",
            },
        ),
    ]
