# Generated by Django 3.2.3 on 2021-06-09 14:11

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_measure_ingredient_dimension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default=recipes.models.random_slug, max_length=20, unique=True, verbose_name='Адрес'),
        ),
    ]
