# Generated by Django 3.2.3 on 2021-06-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_ingredientitem_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientitem',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
