# Generated by Django 3.2.3 on 2021-06-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_rename_ingredients_ingredientitem_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientitem',
            old_name='count',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
    ]
